#! /bin/bash

# Multi word variables
a="this is a car"
b="this is a mercedese"

c="${a} ${b}"

echo "${c}"

# user variable

VAR=$USER
echo "$VAR"

#HOME variable
VAR_PATH=$HOME
echo "$VAR_PATH"

ls "$VAR_PATH"

#Manipulation 
STR="HELLO WORLD!"
echo ${STR,}   #=> "hELLO WORLD!" (lowercase 1st letter)
echo ${STR,,}  #=> "hello world!" (all lowercase)

STR="hello world!"
echo ${STR^}   #=> "Hello world!" (uppercase 1st letter)
echo ${STR^^}  #=> "HELLO WORLD!" (all uppercase)

#String quotes
NAME="John"
n='tom'
echo "Hi $NAME"  #=> Hi John
echo 'Hi $NAME'  #=> Hi 
echo  "$n"

#variables
NAME="John"
echo $NAME
echo "$NAME"
echo "${NAME}!"

#For loop
for ((i = 0 ; i < 10 ; i++)); do
  echo $i
done

users="Linux, Window, Mac"

for user in ${users}
do
    echo "${user}"
done
#While loop
counter=1
while [[ $counter -le 6 ]]
do
    echo $counter
    ((counter++))
done
# Until loop

count=1
until [ $count -gt 6 ]
do
    echo $count
    ((count++))
done

#Ranges
for i in {1..5}; do
    echo "Welcome $i"
done

#Functions

function myfunc() {
    echo "hello $1"
}
myfunc "Avinash"

# Operator Add, subtract, Multiple, Divide
#using expr
num1=10
num2=2

expr $num1 + $num2
expr $num1 - $num2
expr $num1 \* $num2
expr $num1 / $num2

#using echo
num_1=100
num_2=2

echo "$((num_1 + num_2))"
echo "$((num_1 - num_2))"
echo "$((num_1 * num_2))"
echo "$((num_1 / num_2))"
echo "$((num_1 % num_2))"

#using echo user input
read -p "Enter first no:-" num_1
read -p "Enter second no:-" num_2

echo "$((num_1 + num_2))"
echo "$((num_1 - num_2))"
echo "$((num_1 * num_2))"
echo "$((num_1 / num_2))"
echo "$((num_1 % num_2))"


# Echo number modulus
num1=5
num2=2
echo "$((num1 % num2))"
# Echo number exponent

var=$((8**2))
echo $var

